- name: MSMARCO
  corpus_file: # must
  corpus_id_file: # must
  train_query_file: # must
  train_query_id_file: # must
  train_qrels: # must
  neg_file: # Optinal
  teacher_score_files: # Optinal
  sample_neg_from_topk: 200
  train_group_size: 8


- name: NQ
  train_files:
    - biencoder-nq-train.json
    - hn.json
  train_group_size: 8


- name: NLI
  data_file: data/nli_for_simcse.csv
  train_group_size: 8


- name: MEDI
  data_file: /data01/lizehan/embeddings/instructor-embedding/cache/medi-data/medi-data.json
  train_group_size: 2 # useless for now
